sudo: required
services:
  - docker

before_install:
  - docker-compose up -d --build

script:
  - docker-compose exec flaskapp python test_basics.py

after_script:
  - docker-compose down
# after_success:
# - ###
